name: Test all JDKs on all OSes

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8, 11, 15]
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw install --file pom.xml --batch-mode
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Build Gradle Plugin
        run: cd jte-gradle-plugin && ./gradlew publishToMavenLocal
      - name: Test Gradle Plugin Precompile
        run: cd jte-runtime-test-gradle && ./gradlew check
      - name: Test Gradle Plugin Generate
        run: cd jte-runtime-cp-test-gradle && ./gradlew check
      - name: Test Gradle Plugin Generate Pure Kotlin
        run: cd jte-runtime-cp-test-gradle-kotlin && ./gradlew check


  coverage:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw verify --file pom.xml --batch-mode -Pcoverage
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./jte-test-report/target/site/jacoco-aggregate/jacoco.xml
          fail_ci_if_error: true

